### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by billyaraujo** [benzen/angular-bootstrap3-datepicker#11]
"main": [
    "dist/angular-bootstrap3-datepicker.js",
    "dist/angular-bootstrap3-datepicker.min.js",
    "dist/angular-bootstrap3-datepicker.css"],

This isn't consistent with the files in the dist directory:

    "dist/ng-bs3-datepicker.js",
    "dist/ng-bs3-datepicker.min.js",
    "dist/ng-bs3-datepicker.css"

**Comment by benzen** [comment]
Can you propose a PR for this?
I'll be happy to accept it.

Regards

2015-05-06 11:05 GMT-04:00 billyaraujo <notifications@github.com>:

> "main": [
> "dist/angular-bootstrap3-datepicker.js",
> "dist/angular-bootstrap3-datepicker.min.js",
> "dist/angular-bootstrap3-datepicker.css"],
>
> This isn't consistent with the files in the dist directory:
>
> "dist/ng-bs3-datepicker.js",
> "dist/ng-bs3-datepicker.min.js",
> "dist/ng-bs3-datepicker.css"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benzen/angular-bootstrap3-datepicker/issues/11>.
>



-- 
Benjamin Dreux
Analyste-Programmeur
Code³ Coopérative de solidarité
438 777 9250

**Comment by billyaraujo** [comment]
I am not sure you if you want to change the bower.js or the name of the files.

**Comment by benzen** [comment]
In fact, i'm not really really interested into maintaining this package.
I'm looking for a new maintainer, are you interested.
There is not so much to do, still there is work that need to be done.
And i don't have enough time to do it.

As you've noticed, i've merged your PR.

2015-05-06 11:22 GMT-04:00 billyaraujo <notifications@github.com>:

> I am not sure you if you want to change the bower.js or the name of the
> files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benzen/angular-bootstrap3-datepicker/issues/11#issuecomment-99512556>
> .
>



-- 
Benjamin DREUX

**Comment by billyaraujo** [comment]
I don't know much about it really to maintain it. I use it and it suits my needs but I am not sure I could maintain it.

**Comment by tauckenthal** [comment]
@benzen Could you please push these changes to bower, by creating a new release `v1.0.2`?? Currently the latest version doesn't include the bugfix, while master does. Thx :smile:

**Comment by benzen** [comment]
I just added a tag 1.0.3.

Unfortunately I also added a tag 1.0.2, which is just an error, sorry for that.

Tell me if everything works.

**Comment by tauckenthal** [comment]
Works fine. Thx.

**Comment by benzen** [comment]
Great
