### ISSUE TITLE
set min view mode problem

### ISSUE THREAD

**Issue by heyokdang** [benzen/angular-bootstrap3-datepicker#21]
1) When do you click to choose a month then the popup will be closed and date renderred in textbox.
check Min View Mode here: https://eonasdan.github.io/bootstrap-datetimepicker/#min-view-mode

But after i have customized such as below then the popup only closed after i have selected at day, not at month.

2) I have customized your demo code such as below:

- In html i have added  date-view-mode="years":
<ng-bs3-datepicker id="date1" data-ng-model='date1' language="en-ca" date-view-mode="years" date-format="MM/YYYY"/>

- In dp.directive('ngBs3Datepicker'...) i have added some code: var dateViewMode="";
if(e.name === "date-view-mode") {dateViewMode = e.value;} ; viewMode: dateViewMode;

3) This is ngBs3Datepicker directive full code in file ng-bs3-datepicker.js:

dp.directive('ngBs3Datepicker', function($compile) {
  return {
    restrict: 'E',
    replace: true,
    transclude: true,
    template: "<div class='input-group date' >\n  <div style='display:none' class='input-group-addon'>Loan start date</div><input type='text' class='form-control'/>\n  <span class='input-group-addon'>\n    <span class='glyphicon glyphicon-calendar'></span>\n  </span>\n<ng-transclude></ng-transclude></div>",
    link: function($scope, element, attr) {
      var attributes, dateFormat, input, resetValue, dateViewMode;
      dateFormat = "";
      dateViewMode="";
      attributes = element.prop("attributes");
      input = element.find("input");
      resetValue = false;
      angular.forEach(attributes, function(e) {
        if (e.name !== "class") {
        	input.attr(e.name, e.value);
        }
        if (e.name === "date-format") {
        	dateFormat = e.value;
        }

        if(e.name === "date-view-mode") {
        	dateViewMode = e.value;
        }

      });
      $scope.$watch(attr.language, function(value) {
        var language;
        language = value ? value : input.attr('language');
        return input.datetimepicker({
          language: language,
          pickTime: false,
          format: dateFormat,
          viewMode: dateViewMode,
          icons: {
            time: 'fa fa-clock-o',
            date: 'fa fa-calendar',
            up: 'fa fa-arrow-up',
            down: 'fa fa-arrow-down'
          }
        });
      });
      element.find('.input-group-addon').on('click', function(e) {
        return element.find('input').focus();
      });
      /*element.find('input').on('blur',function(e){
      	var x = "foo = 5";
      	eval(x)
      	alert(foo);
      });*/
      element.on("change.dp", function(e) {
        return $scope.$apply(function() {
          var i, obj, objPath, path, _i, _len, _results;
          if (e.date) {
            objPath = attr.ngModel.split(".");
            obj = $scope;
            _results = [];
            for (i = _i = 0, _len = objPath.length; _i < _len; i = ++_i) {
              path = objPath[i];
              if (!obj[path]) {
                obj[path] = {};
              }
              if (i === objPath.length - 1) {
                if (resetValue) {
                  resetValue = false;
                  _results.push(obj[path] = null);
                } else {
                	//e.date.viewMode(dateViewMode);
                	_results.push(obj[path] = e.date.format(dateFormat));
                }
              } else {
                _results.push(obj = obj[path]);
              }
            }
            return _results;
          }
        });
      });
      $scope.$watch(attr.ngModel, function(newValue, oldValue) {
        if (oldValue && !newValue) {
          return resetValue = true;
        }
      });
      return $compile(input)($scope);
    }
  };
});

**Comment by heyokdang** [comment]
i have added more one option: minViewMode, do it similar with viewMode and i have fixed this problem
in html i have added: date-min-view-mode="months", i got done :+1:

**Comment by benzen** [comment]
I'm not quite clear on what your want to do here.
If it's a enhancement proposition and you want to contribute to this project, could you open a pull request it's the best place to share some code that could be integrated to the project.

Many thanks

**Comment by heyokdang** [comment]
i want to upload, but i don't know how to upload my custom code. 

I have tried: 1) fork, 2) download, 3) custom code, 4) commit and get successed. But i can't see any changes on github.
