### ISSUE TITLE
Wrong bower.json main files

### ISSUE THREAD

**Issue by andreptb** [benzen/angular-bootstrap3-datepicker#7]
Hi,

I Believe you forgot to rename bower.json main files section, it still pointing to "angular-bootstrap3-datepicker..." while should be "ng-bs3-datepicker..."

Another nitpick is that the angular module name changed, and  README.md examples is not reflecting it. It should be "ng-bs3-datepicker", not "ng-bootstrap3-datepicker"

**Comment by benzen** [comment]
Oh right, thanks for pointing me this

**Comment by andreptb** [comment]
Take a look at my pull request #9, there I tried to resolve issues #4 and #7
